version: "3"

services:
  frontend:
    image: node:12.2.0-alpine
    command: sh entrypoint.sh

    working_dir: /frontend

    volumes:
      - ./frontend/:/frontend
  nginx:
    image: nginx:latest
    ports:
      - 1233:1233
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
